version: '3.9'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.flask
    # ports:
    #   - "5000:5000"
    expose:
      - "5000"
    networks:
      - aqt-metadata-backend
    restart: always
    depends_on:
      - db
    env_file: .env    

  nginx:
    container_name: nginx
    #image: nginx:1.19.8-alpine
    build:
      context: .
      dockerfile: Dockerfile.nginx
    # volumes:
    #   - aqt-metadata-nginx-conf:/etc/nginx
    ports:
      - "10443:443"
    networks:
      - aqt-metadata-backend
    restart: always
    depends_on:
      - api
      - db

  db:
    container_name: db
    image: mysql:8.0
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    expose: 
      - "3306"
    env_file: .env   
    networks:
      - aqt-metadata-backend
    restart: always    

volumes:
  db_data:

networks:
  aqt-metadata-backend:
    driver: bridge
